FROM envoyproxy/envoy-dev:latest

COPY ./envoy-frontend.yaml /etc/envoy.yaml
COPY ./certs/ca.crt /certs/cacert.pem
COPY ./certs/postgres-frontend-1.example.com.crt /certs/clientcert-1.pem
COPY ./certs/postgres-frontend-2.example.com.crt /certs/clientcert-2.pem
COPY ./certs/example.com.key /certs/clientkey.pem

RUN chmod go+r /etc/envoy.yaml /certs/cacert.pem /certs/clientkey.pem /certs/clientcert-1.pem /certs/clientcert-2.pem
CMD ["/usr/local/bin/envoy", "-c /etc/envoy.yaml", "-l", "debug"]
